// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViberFitBot.WebApi;

#nullable disable

namespace ViberFitBot.ViberApi.Migrations
{
    [DbContext(typeof(TrackContext))]
    [Migration("20220811083836_AddTable_Track")]
    partial class AddTable_Track
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ViberFitBot.WebApi.DbEntities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DistanceMetres")
                        .HasColumnType("float");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<int>("FirstDataId")
                        .HasColumnType("int");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LatestDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FirstDataId")
                        .IsUnique();

                    b.HasIndex("LatestDataId")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("ViberFitBot.WebApi.DbEntities.TrackLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateEvent")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTrack")
                        .HasColumnType("datetime")
                        .HasColumnName("date_track");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IMEI");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(12,9)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(12,9)")
                        .HasColumnName("longitude");

                    b.Property<int>("TypeSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("TrackLocation");
                });

            modelBuilder.Entity("ViberFitBot.WebApi.DbEntities.Track", b =>
                {
                    b.HasOne("ViberFitBot.WebApi.DbEntities.TrackLocation", "FirstData")
                        .WithOne()
                        .HasForeignKey("ViberFitBot.WebApi.DbEntities.Track", "FirstDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViberFitBot.WebApi.DbEntities.TrackLocation", "LatestData")
                        .WithOne()
                        .HasForeignKey("ViberFitBot.WebApi.DbEntities.Track", "LatestDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstData");

                    b.Navigation("LatestData");
                });
#pragma warning restore 612, 618
        }
    }
}
